# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 15:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_needed', models.DecimalField(decimal_places=5, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredienti',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.SmallIntegerField(choices=[(1, 'Piatto'), (2, 'Preparato'), (3, 'Materia prima')])),
                ('is_complete_meal', models.NullBooleanField()),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Scaffale',
                'verbose_name_plural': 'Scaffali',
            },
        ),
        migrations.CreateModel(
            name='UoM',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('readable_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Unità di misura',
                'verbose_name_plural': 'Unità di misura',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Magazzino',
                'verbose_name_plural': 'Magazzino',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Product')),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ricetta',
                'verbose_name_plural': 'Ricette',
            },
        ),
        migrations.AddField(
            model_name='warehouse',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Product'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Shelf'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.UoM'),
        ),
        migrations.AddField(
            model_name='menu',
            name='courses',
            field=models.ManyToManyField(to='core.Product'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set([('product', 'recipe')]),
        ),
    ]
