# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time_needed',
            field=models.TimeField(default=datetime.time(0, 15), verbose_name='Tempo necessario'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='courses',
            field=models.ManyToManyField(to='core.Product', verbose_name='Piatti'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
