# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 09:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170618_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_needed',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tempo necessario (in minuti)'),
        ),
    ]
